spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

aop:
  api-logging:
    enabled: false
  service-performance:
    enabled: false
  transactional-query-logging:
    enabled: false
