spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        session.events.log: false

logging:
  level:
    spring.aop: DEBUG

    # hibernate 로그 설정
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF

    # security 로그 설정
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE